### ISSUE TITLE
如何使用，为何按照文档上面post会400

### ISSUE THREAD

**Issue by ghost** [CDPumpkin/Bx_verification#1]

**Comment by callng** [comment]
[看](https://github.com/CDPumpkin/Bx_verification#%E5%86%B0%E5%BF%83%E7%BD%91%E7%BB%9C%E9%AA%8C%E8%AF%8131%E7%89%88%E6%9C%AC---%E5%AE%89%E8%A3%85%E6%96%B9%E6%B3%95)
