### ISSUE TITLE
本地搭建

### ISSUE THREAD

**Issue by KaSock** [CDPumpkin/Bx_verification#2]
能够进行本地搭建吗？
提示
安装出错:could not find driver

**Comment by KaSock** [comment]
搭建完成后域名/admin/Home/show直接404

**Comment by KaSock** [comment]
![image](https://user-images.githubusercontent.com/56071624/211815300-6682947f-89b8-4326-bf16-c7d1911e7a59.png)

![image](https://user-images.githubusercontent.com/56071624/211815313-4c3b2729-b8db-408c-9708-47a67afcda3b.png)

**Comment by KaSock** [comment]
![image](https://user-images.githubusercontent.com/56071624/211817589-13218999-2edb-4b9d-9ece-18472b379f4b.png)
也确实执行成功了...

**Comment by callng** [comment]
[install](https://github.com/callng/BX_wlyz#%E5%86%B0%E5%BF%83%E7%BD%91%E7%BB%9C%E9%AA%8C%E8%AF%8131%E7%89%88%E6%9C%AC---%E5%AE%89%E8%A3%85%E6%96%B9%E6%B3%95)
